api_version = "2024-10"

[[extensions]]
name = "save-cart-for-later"
handle = "save-cart-for-later"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
api_access = true
network_access = true
storage_access = true
customer_privacy_api = true

[[extensions.metafields]]
namespace = "cart_saver"
key = "saved_items"